version: '3.3'
services:
  # Documentation of properties & policies
  # https://docs.pact.io/pact_broker/docker_images/pactfoundation

  # To deploy on kubernetes
  # https://github.com/ChrisJBurns/pact-broker-chart
  pact-broker:
    image: pactfoundation/pact-broker:2
    container_name: pact-broker
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: pact-db
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_DATABASE_CLEAN_ENABLED: true
      PACT_BROKER_DATABASE_CLEAN_CRON_SCHEDULE: '5 21 * * *'
      PACT_BROKER_DATABASE_CLEAN_KEEP_VERSION_SELECTORS: '[{"latest": true, "max_age": 1}]'
    depends_on:
      - pact-db

  pact-db:
    image: postgres:14.5
    container_name: pact-db
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
