version: '3.3'
services:
  pact-broker:
    image: pactfoundation/pact-broker:2
    container_name: pact-broker
    ports:
      - "9292:9292"
    environment:
      - PACT_BROKER_DATABASE_USERNAME=postgres
      - PACT_BROKER_DATABASE_PASSWORD=password
      - PACT_BROKER_DATABASE_HOST=pact-db
      - PACT_BROKER_DATABASE_NAME=postgres
    depends_on:
      - pact-db

  pact-db:
    image: postgres:13.4
    container_name: pact-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
